<?php

/**
 * UpPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UpPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UpPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UpPlan');
    }
}