<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/09 14:42:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=om',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
